### ISSUE TITLE
Running on Mac OS (macOS Mojave V10.14.6)

### ISSUE THREAD

**Issue by keytonw** [pythonarcade/roguelike#24]
Hi there!

First and foremost, thank you VERY much for your work on the arcade library. It's amazing. Thank you very much. Really looking forward to diving in on a roguelike I've been working on (and finding pygame and other libraries lacking). Trying to get your roguelike example running but having a problem.

I have installed the prerequisites based on the readme. When I run pytest, I get the following:

```
____________________________________ ERROR collecting tests/test_game_window.py _____________________________________
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:986: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:680: in _load_unlocked
    ???
../venvs/arcade/lib/python3.9/site-packages/_pytest/assertion/rewrite.py:171: in exec_module
    exec(co, module.__dict__)
/Users/keyton/Dropbox/fundev/roguelike-master/tests/test_game_window.py:15: in <module>
    ???
source/game_window.py:13: in <module>
    from game_engine import GameEngine
source/game_engine.py:13: in <module>
    from recalculate_fov import recalculate_fov
source/recalculate_fov.py:14: in <module>
    def recalculate_fov(char_x: int, char_y: int, radius: int, sprite_lists: List[arcade.SpriteList[Entity]]):
E   TypeError: 'type' object is not subscriptable
```

When I attempt to run "python source" nothing happens (no errors. just comes back to command line having done nothing)...

In looking at the Real Python article on arcade, I saw that you need to install PyObjC on mac so I did so just in case the requirements.txt file didn't do the trick...

I am running Python 3.9.1 as indicated in the error above.

Screen when attempting to run pytest:

![Screen Shot 2020-12-04 at 11 47 59 AM](https://user-images.githubusercontent.com/15663318/101190609-97e5a980-3626-11eb-9b30-18171484a178.png)

Screen when attempting to do a python source:
![Screen Shot 2020-12-04 at 11 48 38 AM](https://user-images.githubusercontent.com/15663318/101190667-ae8c0080-3626-11eb-961c-e7aed60e6833.png)

I'm running in a virtual machine called "arcade"

**Comment by pvcraven** [comment]
Fix has been pushed. Thanks.
