### ISSUE TITLE
Bits of dead code

### ISSUE THREAD

**Issue by filiplajszczak** [pythonarcade/roguelike#3]
While reading the code and doing #1 I was confused for a moment only to realize that  `entities.entity.Entity.move_towards` and `procedural_generation.game_map.GameMap.is_blocked` are the dead code and artifacts of the previous implementation. Is there a plan to use it in the future in some modified way or could it be safely removed?

**Comment by pvcraven** [comment]
Artifact from the tutorial. Needs to be removed.
